trigger:
- master
- develop

variables:
  serviceConnection: 'InnofactorManagedComponents-ServiceConnection'
  functionAppName: 'func-secretmanagementservice-development-001'
  vmImageName: 'ubuntu-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/SecretManagementService'
  resourceGroup: 'LIA-ResourceGroup'

  # Environment variables
  keyVaultUri: 'https://sms-appsecrets.vault.azure.net/'
  clientId: '4e72630e-e7a9-444f-8287-c7b704149746'
  tenantId: 'd87548be-2c3c-454d-8214-8941643fc99f'
  environment: 'Development'
  hostId: 'func-secretmgmt-dev-001'
  daysUntilSecretsExpire: '30'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - script: |
        dotnet restore
        dotnet build --configuration Release
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.0.x'
        includePreviewVersions: true

    - task: DotNetCoreCLI@2
      displayName: 'Publish Function App'
      inputs:
        command: 'publish'
        publishWebProjects: false
        arguments: '--configuration Release --output publish_output'
        projects: '$(workingDirectory)/*.sln'
        modifyOutputPath: false
        zipAfterPublish: false

    - task: ArchiveFiles@2
      displayName: 'Zip published output'
      inputs:
        rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
        includeRootFolder: false
        archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip'
        artifact: 'drop'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: Deploy
    displayName: Deploy to Azure Function
    environment: 'development'
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureFunctionApp@2
            displayName: 'Deploy Function App'
            inputs:
              isFlexConsumption: true
              azureSubscription: $(serviceConnection)
              appType: functionAppLinux
              appName: $(functionAppName)
              package: $(System.ArtifactsDirectory)/**/*.zip
              deploymentMethod: 'auto'
              appSettings: >
                -KEY_VAULT_URI $(keyVaultUri)
                -CLIENT_ID $(clientId)
                -TENANT_ID $(tenantId)
                -AzureFunctionsWebHost__hostid $(hostId)
                -ASPNETCORE_ENVIRONMENT $(environment)
                -DAYS_UNTIL_SECRET_EXPIRES $(daysUntilSecretsExpire)

